name: APK Derle

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-android:
    name: Android APK olustur
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v4

      - name: Build with Buildozer (Docker)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/home/user/app \
            -w /home/user/app/pyrunner_app \
            --user $(id -u):$(id -g) \
            --entrypoint /bin/bash \
            ghcr.io/kivy/buildozer:latest -c "source /home/user/.venv/bin/activate && buildozer -v android debug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyrunner-apk
          path: bin/*.apk
