name: APK Derle

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-android:
    name: Android APK olustur
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v4

      - name: Build with Buildozer (Docker)
        run: |
          docker run --rm -v "${{ github.workspace }}":/home/user/app -w /home/user/app ghcr.io/kivy/buildozer:latest /bin/bash -c "buildozer -v android debug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyrunner-apk
          path: bin/*.apk
